ExamProject/apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^create/$', views.create, name="create"),
    url(r'^dashboard/$', views.process, name="dashboard"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^login/$', views.login, name="login"),
    url(r'^addJob/$', views.addJob, name="addJob"),
    url(r'^registerJob/$', views.registerJob, name="registerJob"),
    url(r'^editJob/(?P<job_id>\d+)$', views.editJob, name="editJob"),
    url(r'^updateJob/(?P<job_id>\d+)$', views.updateJob, name="updateJob"),
    url(r'^view/(?P<job_id>\d+)$', views.view, name="view"),
    url(r'^registerMyJob/(?P<job_id>\d+)$', views.registerMyJob, name="registerMyJob"),
    url(r'^remove/(?P<job_id>\d+)$', views.remove, name="remove"),
    url(r'^done/(?P<job_id>\d+)$', views.done, name="done")
]

ExamProject/belt_exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.main.urls', namespace="jobs"))
]

ExamProject/apps/main/models.py
from django.db import models

# Create your models here.

from django.db import models

# Create your models here.
import bcrypt
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')


class UserManager(models.Manager):
    # models.Manager has filter function, .all
    def validate(self, form):
        errors = []
        if len(form['first_name']) < 2:
            errors.append("First name must be at least 2 characters long.")

        if len(form['last_name']) < 2:
            errors.append("Last name must be at least 2 characters long.")

        if len(form['password']) < 8 & len(form['confirm_password']) < 8:
            errors.append("Password must be at least 8 characters long.")

        if form['password'] != form['confirm_password']:
            errors.append("You need to confirm the password!")

        if not EMAIL_REGEX.match(form['email']):
            errors.append("Must be a valid email address.")

        # try:
        #     User.objects.get(email=form['email'])
        #     error.append('Email already in use')
        # except:

        existing_email = User.objects.filter(email=form['email'])
        if existing_email:
            errors.append("Email already in use")
            print(existing_email)

        # select queries

        # User.objects.get = will return to us either the specific single thing that exist in db with that parameter  -  the prob: if there are more than one -
        # you get an error - if there isn;t anything it throws error

         # User.objects.filter
        # User.objects.exclude  = not inclde the things that match
        # User.objects.all = has no filter parameters
        return errors

    def easy_create(self, form):
        # hash password
        hashed_pw = bcrypt.hashpw(form['password'].encode(),
                                  bcrypt.gensalt())
        # create
        user = User.objects.create(
            first_name=form['first_name'],
            last_name=form['last_name'],
            email=form['email'],
            pw_hash=hashed_pw
        )

        # return id
        return user.id

    def login(self, form):
        existing_users = User.objects.filter(email=form['email'])

        if existing_users:
            user = existing_users[0]
            if bcrypt.checkpw(form['password'].encode(), user.pw_hash.encode()):
                return(True, user.id)
        return(False, "Email or password incorrect!")


class User(models.Model):
    # When we inherit from a class - get all attributes and the methods we are inheriting from
    # give us the init function from Model...
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    '''
     We are not using __init__() ...
     1. We don't want to override the init method - we are using the one
        we inheritted
     2. This syntax first_name = ... without putting inside the init
        we are saying that this is a property of the class, not of specific object
     '''
    email = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # shadow column "tweets" - list of tweets - reference to the tweet table
    objects = UserManager()

    def __repr__(self):
        return "<User: %s>" % self.first_name

    def __str__(self):
        return "<User: %s>" % self.first_name


class JobManager(models.Manager):

    def validate(self, form):
        errors = []
        if len(form['title']) < 3:
            errors.append("Title must be at least 3 characters long.")

        if len(form['description']) < 10:
            errors.append("Description must be at least 10 characters long.")

        if len(form['location']) <= 0:
            errors.append("Location must not be blank.")

        return errors

    def easy_create(self, form, user_id):

        if 'user_id' in form: 

            user = User.objects.get(id=user_id)
            JobByUser.objects.create(
                user=user,
                job=Job.objects.create(
                    title=form['title'],
                    location=form['location'],
                    description=form['description'],
                )
            )
        else: 
            Job.objects.create(
                title=form['title'],
                location=form['location'],
                description=form['description'],
            )

        # return id
        # return job.id
    def updated_job(self, form, job_id):
        job = Job.objects.get(id=job_id)
        print(job)
        job.title = form['title']
        job.description = form['description']
        job.location = form['location']
        job.save()
        return job


class Job(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    location = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = JobManager()

    def __repr__(self):
        return "<Job: %s>" % self.title

    def __str__(self):
        return "<Job: %s>" % self.title


class JobByUserManager(models.Manager):

    def registerMyJob(self, job_id, user_id):

        # Job.objects.exclude(job_by_user__user=user_id)
        user = User.objects.get(id=user_id)

        job = Job.objects.get(id=job_id)
        JobByUser.objects.create(
            user=user,
            job=job
        )

        # job.delete()


class JobByUser(models.Model):
    user = models.ForeignKey(User, related_name="jobs_by_user")
    job = models.ForeignKey(Job, related_name="job_by_user")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = JobByUserManager()

ExamProject/apps/main/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.contrib import messages
from .models import User, Job, JobByUser
# Create your views here.


def index(request):
    if 'user_id' not in request.session:
        return render(request, 'main/index.html')

    return redirect('jobs:dashboard')


def create(request):
    print(request.POST)

    errors = User.objects.validate(request.POST)

    if errors:
        for error in errors:
            messages.error(request, error)

        return redirect('jobs:index')

    user_id = User.objects.easy_create(request.POST)

    request.session['user_id'] = user_id
    print('SESSION USER ID: ', request.session['user_id'])
    return redirect('jobs:dashboard')


def process(request):
    if 'user_id' not in request.session:
        return redirect('jobs:index')

    context = {
        "user": User.objects.get(id=request.session['user_id']),
        "jobs": Job.objects.all() & Job.objects.exclude(job_by_user__user=request.session['user_id']),
        "jobs_by_user": JobByUser.objects.all()
    }

    return render(request, 'main/dashboard.html', context)


def logout(request):
    request.session.clear()
    return redirect('jobs:index')

def login(request):
    valid, result = User.objects.login(request.POST)

    if not valid:
        messages.error(request, result)
        return redirect('jobs:index')

    request.session['user_id'] = result
    return redirect('jobs:dashboard')


def addJob(request):
    return render(request, 'main/add_job.html')


def registerJob(request):
    print(request.POST)

    errors = Job.objects.validate(request.POST)

    if errors:
        for error in errors:
            messages.error(request, error)

        return redirect('jobs:addJob')


    user_id = request.session['user_id']
    Job.objects.easy_create(request.POST, user_id)
    # request.session['job'] = job_id
    return redirect('jobs:dashboard')


def view(request, job_id):

    context = {
        "job": Job.objects.get(id= job_id)
    }
    return render(request, 'main/view_job.html', context)


def registerMyJob(request, job_id):

    # jobs= Job.objects.exclude(job_by_user__user=request.session['user_id'])

    # request.session['jobs'] = jobs
    user_id = request.session['user_id']
    JobByUser.objects.registerMyJob(job_id, user_id)
    return redirect('jobs:dashboard')


def remove(request, job_id):
    job = Job.objects.get(id=job_id)

    job.delete()
    return redirect('jobs:dashboard')


def done(request, job_id):

    from_me = JobByUser.objects.filter(job=job_id)
    if from_me:
        from_me.delete()
        me = Job.objects.get(id=job_id)
        me.delete()
    else:
        job = Job.objects.get(id=job_id)
        job.delete()
    return redirect('jobs:dashboard')


def editJob(request, job_id):
    job = Job.objects.get(id = job_id)
    context = {
        "job": job
    }
    return render(request, 'main/edit_job.html', context)

def updateJob(request, job_id):
    updated_job = Job.objects.updated_job(request.POST, job_id)
    return redirect(reverse('jobs:editJob', kwargs={"job_id": updated_job.id}))

ExamProject/apps/main/templates/main/add_job.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="">
          <img src="https://image4.owler.com/logo/coding-dojo_owler_20161201_092020_original.png" width="112"
            height="28">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
          data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Add a Job
          </a>
          <div class="navbar-item has-dropdown is-hoverable">
          </div>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a href="{% url 'jobs:dashboard' %}" class="button is-gray is-small is-outlined">Back</a>
              <a href="{% url 'jobs:logout' %}" class="navbar-item button is-gray is-medium is-outlined">Logout</a>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section">
      <h1 class="title">
        Add Job
      </h1>
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }} has-text-danger">{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <div class="box">
        <form action="{% url 'jobs:registerJob' %}" method="POST">
          {% csrf_token %}
          <div class="field">
            <label class="label">Title</label>
            <div class="control">
              <input class="input" name="title" type="text" placeholder="">
            </div>
          </div>
          <div class="field">
            <label class="label">Description</label>
            <div class="control">
              <textarea class="textarea" name="description" placeholder=""></textarea>
            </div>
          </div>
          <div class="field">
            <label class="label">Location</label>
            <div class="control">
              <input class="input" name="location" type="text" placeholder="">
            </div>
          </div>
          <label class="checkbox">
            <input type="checkbox" name="user_id">
            By me
          </label>
          <input type="submit" class="button is-info is-outlined is-small" value="Submit" />
        </form>

      </div>
    </section>
  </div>
</body>

</html>

ExamProject/apps/main/templates/main/dashboard.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}
    <section class="section">
      <div class="columns">
        <div class="column">
          <table class="table">
            <thead>
              <tr>
                <th><abbr title="Position">Job</abbr></th>
                <th>Location</th>
                <th><abbr title="Played">Action</abbr></th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th><abbr title="Position">Job</abbr></th>
                <th>Location</th>
                <th><abbr title="Played">Action</abbr></th>
              </tr>
            </tfoot>
            <tbody>
              {% for job in jobs %}
              <tr>
                <th>{{ job.title }}</th>
                <td>{{ job.location }}<strong></strong></td>
                <td>
                  <a href="{% url 'jobs:view' job.id %}" class="button is-text is-outlined">View</a>
                  <a href="{% url 'jobs:registerMyJob' job.id %}" class="button is-text is-outlined">Add</a>
                  <a href="{% url 'jobs:editJob' job.id %}" class="button is-text is-outlined">Edit</a>
                  <a href="{% url 'jobs:remove' job.id %}" class="button is-text is-outlined">Cancel</a>
                {% if job.job_by_user == request.session.user_id %}
                {% endif  %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

        </div>
        <div class="column">
          <table class="table">
            <thead>
              <tr>
                <th><abbr title="Position">Job</abbr></th>
                <th>Location</th>
                <th><abbr title="Played">Action</abbr></th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th><abbr title="Position">Job</abbr></th>
                <th>Location</th>
                <th><abbr title="Played">Action</abbr></th>
              </tr>
            </tfoot>
            <tbody>
              {% for job in jobs_by_user %}
              <tr>
                <th>{{ job.job.title }}</th>
                <td>{{ job.job.location }}<strong></strong></td>
                <td>
                    <a href="{% url 'jobs:view' job.job.id %}" class="button is-text is-outlined">View</a>
                    <a href="{% url 'jobs:done' job.job.id %}" class="button is-text is-outlined">Done</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

        </div>
      </div>
    </section>
  </div>
</body>

</html>

ExamProject/apps/main/templates/main/edit_job.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="">
          <img src="https://image4.owler.com/logo/coding-dojo_owler_20161201_092020_original.png" width="112"
            height="28">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
          data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Add a Job
          </a>
          <div class="navbar-item has-dropdown is-hoverable">
          </div>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a href="{% url 'jobs:dashboard' %}" class="button is-gray is-small is-outlined">Back</a>
              <a href="{% url 'jobs:logout' %}" class="navbar-item button is-gray is-medium is-outlined">Logout</a>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section">
      <h1 class="title">
        Add Job
      </h1>
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }} has-text-danger">{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <div class="box">
        <form action="{% url 'jobs:updateJob' job.id %}" method="POST">
          {% csrf_token %}
          <div class="field">
            <label class="label">Title</label>
            <div class="control">
              <input class="input" name="title" type="text" placeholder="" value="{{ job.title }}">
            </div>
          </div>
          <div class="field">
            <label class="label">Description</label>
            <div class="control">
              <textarea class="textarea" name="description" value="{{ job.description }}">{{ job.description }}</textarea>
            </div>
          </div>
          <div class="field">
            <label class="label">Location</label>
            <div class="control">
              <input class="input" name="location" type="text" placeholder="" value="{{ job.location }}">
            </div>
          </div>
          <input type="submit" class="button is-info is-outlined is-small" value="Submit" />
        </form>

      </div>
    </section>
  </div>
</body>

</html>

ExamProject/apps/main/templates/main/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Belt Exam</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}
    <section class="section">
      <h1 class="title">
        Welcome to Handy Helper
        <a href="" class="button is-grey is-text">Back to dashboard</a>
      </h1>
      <div class="columns">
        <div class="column">
          <h1 class="subtitle">
            Register
          </h1>
          <div class="box">
            <form action="{% url 'jobs:create' %}" method="POST">
              {% csrf_token %}
              
              <div class="field">
                <label class="label">First Name</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" name="first_name" type="text" placeholder="">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="fas fa-check"></i>
                  </span>
                </div>
              </div>
              <div class="field">
                <label class="label">Last Name</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" name="last_name" type="text" placeholder="">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="fas fa-check"></i>
                  </span>
                </div>
              </div>
              
              <div class="field">
                <label class="label">Email</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" name="email" type="email" placeholder="Email input"
                    value="{{ edit_user.email }}">
                  <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="fas fa-exclamation-triangle"></i>
                  </span>
                </div>
              </div>
              <div class="field">
                  <label class="label">Password</label>
                  <p class="control has-icons-left">
                    <input class="input" name="password" type="password" placeholder="Password">
                    <span class="icon is-small is-left">
                      <i class="fas fa-lock"></i>
                    </span>
                  </p>
                </div>
                <div class="field">
                  <label class="label">Confirm Password</label>
                  <p class="control has-icons-left">
                    <input class="input" name="confirm_password" type="password" placeholder="Confirm Password">
                    <span class="icon is-small is-left">
                      <i class="fas fa-lock"></i>
                    </span>
                  </p>
                </div>

              <input type="submit" class="button is-primary" value="Save" />
            </form>
          </div>

        </div>
        <div class="column">
          <h1 class="subtitle">
            Login
          </h1>

          <div class="box">
            <form action="{% url 'jobs:login' %}" method="POST">
              {% csrf_token %}
              <div class="field">
                  <label class="label">Email</label>
                  <div class="control has-icons-left has-icons-right">
                    <input class="input" name="email" type="email" placeholder="Email input"
                      value="{{ edit_user.email }}">
                    <span class="icon is-small is-left">
                      <i class="fas fa-envelope"></i>
                    </span>
                    <span class="icon is-small is-right">
                      <i class="fas fa-exclamation-triangle"></i>
                    </span>
                  </div>
                </div>
                <div class="field">
                    <label class="label">Password</label>
                    <p class="control has-icons-left">
                      <input class="input" name="password" type="password" placeholder="Password">
                      <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                      </span>
                    </p>
                  </div>
              <input type="submit" class="button is-primary" value="Save" />
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
</body>

</html>

ExamProject/apps/main/templates/main/nav.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="">
      <img src="https://image4.owler.com/logo/coding-dojo_owler_20161201_092020_original.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
      data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

      {% if request.session.user_id %}
      <a class="navbar-item">
        Welcome {{ user.first_name }}
      </a>

      <a href="{% url 'jobs:logout' %}" class="navbar-item button is-gray is-medium is-outlined">Logout</a>

      {% endif %}


      <div class="navbar-item has-dropdown is-hoverable">

      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if request.session.user_id %}

          <a href="{% url 'jobs:addJob' %}" class="navbar-item">
            Add a Job
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

ExamProject/apps/main/templates/main/view_job.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="">
          <img src="https://image4.owler.com/logo/coding-dojo_owler_20161201_092020_original.png" width="112"
            height="28">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
          data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
     >
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a href="{% url 'jobs:dashboard' %}" class="button is-gray is-small is-outlined">Back</a>
              <a href="" class="navbar-item button is-gray is-medium is-outlined">Logout</a>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section">
      <div class="column is-half">

        <form action="">
        <div class="box">
          <h1 class="title">
            {{ job.title }}
          </h1>
          <p class="subtitle">
            {{ job.description }} <strong></strong>!
          </p>
          
          <p class="subtitle">
            Location: {{ job.location }} <strong></strong>!
          </p>
          
          <p class="subtitle">
            Posted on: {{ job.created_at }} <strong></strong>!
          </p>
  
        </div>
        <a href="{% url 'jobs:registerMyJob' job.id %}" class="button is-gray is-small is-outlined">Add to my jobs</a>
      </form>
      </div>
    </section>
  </div>
</body>

</html>